# Generated by Django 4.0.6 on 2022-08-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('AMD', 'AMD'), ('RUR', 'RUR')], default='AMD', max_length=3),
        ),
    ]
