# Generated by Django 4.0.6 on 2022-08-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0005_remove_event_company_event_time_from_event_time_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_to',
        ),
    ]
