# Generated by Django 4.0.6 on 2022-08-03 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0006_remove_event_date_from_remove_event_date_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 3, 18, 20, 59, 68105, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
