# Generated by Django 4.0.6 on 2022-08-03 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0007_event_event_date_event_time_from_event_time_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 3, 18, 21, 42, 341340, tzinfo=utc)),
        ),
    ]
