# Generated by Django 4.0.6 on 2022-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0009_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=85),
        ),
    ]
