# Generated by Django 4.0.6 on 2022-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0010_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_event',
            field=models.URLField(blank=True),
        ),
    ]
