# Generated by Django 4.0.6 on 2022-10-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0011_event_url_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url_event',
            new_name='url',
        ),
    ]
